/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    description: 'Salário',
    amount: '1300.52',
    type: 'entrada',
    frequency: 'recorrente',
    date: '2015-01-10',
  },
  {
    description: 'Freela',
    amount: '150.13',
    type: 'entrada',
    frequency: 'eventual',
    date: '2016-01-17',
  },
  {
    description: 'Salário',
    amount: '2500.23',
    type: 'entrada',
    frequency: 'recorrente',
    date: '2018-02-10',
  },
  {
    description: 'Freela site',
    amount: '900.23',
    type: 'entrada',
    frequency: 'eventual',
    date: '2020-02-21',
  },
  {
    description: 'Freela app',
    amount: '950.92',
    type: 'entrada',
    frequency: 'eventual',
    date: '2020-02-23',
  },
  {
    description: 'Salário',
    amount: '7200.36',
    type: 'entrada',
    frequency: 'recorrente',
    date: '2020-02-28',
  },
  {
    description: 'Salário',
    amount: '2500.25',
    type: 'entrada',
    frequency: 'recorrente',
    date: '2021-03-10',
  },
  {
    description: 'Salário',
    amount: '2500.18',
    type: 'entrada',
    frequency: 'recorrente',
    date: '2021-04-10',
  },
  {
    description: 'Indenização',
    amount: '2500.18',
    type: 'entrada',
    frequency: 'recorrente',
    date: '2022-01-10',
  },
];
